<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Восстановление пароля</title>
</head>
<body>


</div>
<p>Registration <a href="/registration"> here</a></p>

<div><label> Новый пароль: <input type="password" name="password" id="pass"/> </label></div>
<div><label> Повторите пароль: <input type="password" name="password" id="repass"/> </label></div>
<div>
    <button onclick="send_data()">
           Изменить пароль
    </button>
</div>
<div id="massage"></div>
</body>
</html>